### ISSUE TITLE
Error receiving data from IS when libthrift version is upgraded to 0.12.0 

### ISSUE THREAD

**Issue by dilin993** [wso2/analytics-is#461]
I have tried to upgrade the libthrift version in the master branch of "carbon-analytics-common". But when I ran a functionality test with the IS analytics pack, the following error was observed whenever data was published from IS.

```ERROR {org.apache.thrift.server.TThreadPoolServer} - Thrift error occurred during processing of message. org.apache.thrift.transport.TTransportException
at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425)
at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321)
at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225)
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)```

This error was observed for the following combination of tests.
Thrift updated IS(5.8.0-alpha)  --> Thrift Updated IS analytics
Latest IS(5.8.0-alpha) with older thrift version --> Thrift Updated IS analytics
Wum updated IS 5.7.0 --> Thrift Updated IS analytics
Other combinations did not result this error. Therefore we can isolate that this error is occurring due to upgrading the thrift version.

**Comment by dilin993** [comment]
https://github.com/wso2/carbon-analytics-common/issues/603
