### ISSUE TITLE
PostgreSQL configuration issue with Dashboard

### ISSUE THREAD

**Issue by Manasha11** [wso2/analytics-is#498]
**Description:**
When configuring PostgresSQL 9.6 for the IS analytics 5.8.0, the following error occurs on startup of the dashboard node.
```
WARN {org.wso2.carbon.dashboards.core.internal.DashboardImporter} - Cannot save dashboard importing from '/home/manasha/Desktop/Amore/wso2is-analytics-5.8.0/wso2/dashboard/resources/dashboards/is-analytics.json' to the database. org.wso2.carbon.dashboards.core.exception.DashboardException: Cannot create a new dashboard with DashboardMetadata{url='is-analytics', owner='admin', name='IS Analytics'}'.
	at org.wso2.carbon.dashboards.core.internal.database.DashboardMetadataDao.add(DashboardMetadataDao.java:171)
	at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.add(DashboardMetadataProviderImpl.java:172)
	at org.wso2.carbon.dashboards.core.internal.DashboardImporter.importDashboards(DashboardImporter.java:78)
	at org.wso2.carbon.dashboards.core.internal.DashboardMetadataProviderImpl.init(DashboardMetadataProviderImpl.java:111)
	at org.wso2.carbon.dashboards.api.internal.DashboardRestApiProvider.getMicroservices(DashboardRestApiProvider.java:83)
	at org.wso2.carbon.uiserver.internal.deployment.listener.RestApiDeployer.collectMicroservices(RestApiDeployer.java:127)
	at org.wso2.carbon.uiserver.internal.deployment.listener.RestApiDeployer.appDeploymentEvent(RestApiDeployer.java:86)
	at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.publishAppDeploymentEvent(ArtifactAppDeployer.java:154)
	at org.wso2.carbon.uiserver.internal.io.deployment.ArtifactAppDeployer.deploy(ArtifactAppDeployer.java:103)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createBlob() is not yet implemented.
	at org.postgresql.Driver.notImplemented(Driver.java:692)
	at org.postgresql.jdbc.PgConnection.createBlob(PgConnection.java:1361)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.createBlob(HikariConnectionProxy.java)
	at org.wso2.carbon.dashboards.core.internal.database.DashboardMetadataDao.add(DashboardMetadataDao.java:163)
	... 21 more

```

**Affected Product Version:**
WSO2 IS Analytics 5.8.0

**OS, DB, other environment details and versions:**    
PostgreSQL 9.6
Postgres JDBC driver version 42.2.14

**Steps to reproduce:**`
1. Configure PostgreSQL for the WSO2_DASHBOARD_DB datasource in wso2is-analytics-home/conf/dashboard/deployment.yaml file.
2. Start the WSO2 IS server.
3. Start the Worker node.
4. Start the Dashboard node.

**Comment by mefarazath** [comment]
Similar to https://github.com/wso2/analytics-is/issues/497

**Comment by Buddhimah** [comment]
Public fix: https://github.com/wso2/carbon-dashboards/pull/1191

**Comment by Avarjana** [comment]
Closing since this repository is no longer maintained. Analytics IS was replaced by ELK analytics with https://github.com/wso2-extensions/identity-elk-integration.
